apexchartsCardTemplates:
  default:
    header:
      show: true
      title: My Title
      showStates: true
      colorizeStates: true
    show:
      loading: true
      lastUpdated: true
    now:
      show: true
      label: Now
    allSeriesConfig:
      show:
        legendValue: true
    allYaxisConfig:
      minValue: "|-10|"
      maxValue: "|+10|"
      alignTo: 1
      apexConfig:
        tickAmount: 6
    apexConfig:
      legend:
        showForSingleSeries: true
      tooltip:
        x:
          format: dd MMM yyyy, HH:mm
      xaxis:
        axisBorder:
          show: false
        axisTicks:
          show: false
        tooltip:
          enabled: false
        crosshairs:
          show: false
        labels:
          show: true
          datetimeFormatter:
            day: dd MMM
            hour: HH:mm
  baseTemperature:
    configTemplates: default
    header:
      title: Temperature
    allYaxisConfig:
      minValue: "|-5|"
      maxValue: "|+5|"
    dataTypes:
      - id: temperature
        clampNegative: true
        floatPrecision: 0
        unit: "°C"
      - id: humidity
        clampNegative: true
        floatPrecision: 0
        unit: "%"
    yAxes:
      - id: temperature
        dataTypeId: temperature
      - id: humidity
        dataTypeId: humidity
        opposite: true
  baseEnergyPower:
    configTemplates: default
    dataTypes:
      - id: power
        clampNegative: true
        floatPrecision: 2
        unitStep: 1000
        unitArray:
          - W
          - kW
          - MW
          - GW
      - id: energy
        clampNegative: true
        floatPrecision: 2
        unitStep: 1000
        unitArray:
          - Wh
          - kWh
          - MWh
          - GWh
    allYaxisConfig:
      alignTo: 10
  basePower:
    configTemplates: baseEnergyPower
    header:
      title: Power
  baseEnergy:
    configTemplates: baseEnergyPower
    header:
      title: Energy
    allSeriesConfig:
      type: column
      show:
        legendFunction: sum
title: Home
views:
  - path: default_view
    title: Home
    badges: []
    cards:
      - type: custom:apexcharts-card
        configTemplates: baseEnergy
        header:
          title: Server Rack Energy New 1
        entity: button.graph_entities_server_rack_energy
        yAxes:
          - dataTypeId: energy
      - type: custom:apexcharts-card
        configTemplates: baseEnergy
        header:
          title: Server Rack Energy New 2
        entity: button.graph_entities_server_rack_energy_2
        yAxes:
          - id: energy
            dataTypeId: energy
          - id: power
            dataTypeId: power
            opposite: true
      - type: custom:apexcharts-card
        configTemplates: baseTemperature
        header:
          title: Server Rack Temp
        entity: button.graph_entities_server_rack_temperature_humidity
        yAxes:
          - id: temperature
            dataTypeId: temperature
          - id: humidity
            dataTypeId: humidity
            opposite: true
  # - path: panel
  #   title: Panel
  #   badges: []
  #   panel: true
  #   cards:
  #     - type: custom:apexcharts-card-2
  #       configTemplates: baseEnergy
  #       header:
  #         title: Server Rack Energy x
  #       entity: button.graph_entities_server_rack_energy
