/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const ChartCardExternalConfig = t.iface([], {
  type: t.lit("custom:apexcharts-card-2"),
  entity: "string",
  config_templates: t.opt(t.union(t.array("string"), "string")),
  color_list: t.opt(t.array("string")),
  chart_type: t.opt("ChartCardChartType"),
  update_interval: t.opt("string"),
  update_delay: t.opt("string"),
  all_series_config: t.opt("ChartCardAllSeriesExternalConfig"),
  series: t.opt(t.array("ChartCardSeriesExternalConfig")),
  span_generator: t.opt("string"),
  now: t.opt(
    t.iface([], {
      show: t.opt("boolean"),
      color: t.opt("string"),
      label: t.opt("string"),
    }),
  ),
  show: t.opt(
    t.iface([], {
      loading: t.opt("boolean"),
      last_updated: t.opt("boolean"),
    }),
  ),
  stacked: t.opt("boolean"),
  apex_config: t.opt("any"),
  header: t.opt("ChartCardHeaderExternalConfig"),
  yaxis: t.opt(t.array("ChartCardYAxisExternal")),
});

export const ChartCardChartType = t.union(t.lit("line"), t.lit("scatter"));

export const ChartCardSpanExtConfig = t.iface([], {
  start: t.opt("ChartCardStartEnd"),
  end: t.opt("ChartCardStartEnd"),
  offset: t.opt("string"),
});

export const ChartCardStartEnd = t.union(
  t.lit("minute"),
  t.lit("hour"),
  t.lit("day"),
  t.lit("week"),
  t.lit("month"),
  t.lit("year"),
  t.lit("isoWeek"),
);

export const ChartCardAllSeriesExternalConfig = t.iface([], {
  entity: t.opt("string"),
  attribute: t.opt("string"),
  name: t.opt("string"),
  type: t.opt(t.union(t.lit("line"), t.lit("column"), t.lit("area"))),
  color: t.opt("string"),
  opacity: t.opt("number"),
  curve: t.opt(t.union(t.lit("smooth"), t.lit("straight"), t.lit("stepline"))),
  stroke_width: t.opt("number"),
  extend_to: t.opt(t.union(t.lit(false), t.lit("end"), t.lit("now"))),
  clamp_negative: t.opt("boolean"),
  unit: t.opt("string"),
  unit_step: t.opt("number"),
  unit_array: t.opt(t.array("string")),
  unit_separator: t.opt("string"),
  data_generator: t.opt("string"),
  float_precision: t.opt("number"),
  min: t.opt("number"),
  max: t.opt("number"),
  show: t.opt("ChartCardSeriesShowConfigExt"),
  yaxis_id: t.opt("string"),
});

export const ChartCardSeriesShowConfigExt = t.iface([], {
  legend_value: t.opt("boolean"),
  legend_function: t.opt(t.union(t.lit("last"), t.lit("sum"))),
  in_header: t.opt(
    t.union("boolean", t.lit("raw"), t.lit("before_now"), t.lit("after_now")),
  ),
  name_in_header: t.opt("boolean"),
  in_chart: t.opt("boolean"),
  datalabels: t.opt(t.union("boolean", t.lit("total"), t.lit("percent"))),
  extremas: t.opt(
    t.union(
      "boolean",
      t.lit("time"),
      t.lit("min"),
      t.lit("max"),
      t.lit("min+time"),
      t.lit("max+time"),
    ),
  ),
});

export const ChartCardSeriesExternalConfig = t.iface(
  ["ChartCardAllSeriesExternalConfig"],
  {
    entity: "string",
  },
);

export const ChartCardHeaderExternalConfig = t.iface([], {
  show: t.opt("boolean"),
  floating: t.opt("boolean"),
  title: t.opt("string"),
  show_states: t.opt("boolean"),
  colorize_states: t.opt("boolean"),
  standard_format: t.opt("boolean"),
});

export const ChartCardYAxisExternal = t.iface([], {
  id: t.opt("string"),
  show: t.opt("boolean"),
  opposite: t.opt("boolean"),
  min: t.opt(t.union(t.lit("auto"), "number", "string")),
  max: t.opt(t.union(t.lit("auto"), "number", "string")),
  align_to: t.opt("number"),
  decimals: t.opt("number"),
  apex_config: t.opt("any"),
});

const exportedTypeSuite: t.ITypeSuite = {
  ChartCardExternalConfig,
  ChartCardChartType,
  ChartCardSpanExtConfig,
  ChartCardStartEnd,
  ChartCardAllSeriesExternalConfig,
  ChartCardSeriesShowConfigExt,
  ChartCardSeriesExternalConfig,
  ChartCardHeaderExternalConfig,
  ChartCardYAxisExternal,
};
export default exportedTypeSuite;
